### ISSUE TITLE
How to ignore punctuation symbols

### ISSUE THREAD

**Issue by glebov21** [aarondandy/WeCantSpell.Hunspell#75]
Hello. I have a text: **"Hello, my name is Bob. How do you do?"**
I use `Split(' ');` and do `Check` for all words. But how can i ignore: comma, dot and question in `Check` method?

Maybe this library have properties for this? Or i must use regex?

**Comment by funex** [comment]
Have a look at [ICU4N](https://github.com/NightOwl888/ICU4N). I suggest that you use breakiterator class to identify the word boundaries and spellcheck them one by one.

**Comment by glebov21** [comment]
> Have a look at [ICU4N](https://github.com/NightOwl888/ICU4N) or [ICU.Net](https://github.com/sillsdev/icu-dotnet). I suggest that you use breakiterator class to identify the word boundaries and spellcheck them one by one. [Some examples in Java](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/)

additional library for remove punctuation? No, thanks. I will use regex or loop for this :)

**Comment by funex** [comment]
I would probably close/reject this one since "parsing" the terms to be spellchecked isn't really what this library is supposed to do. Identifying word boundaries for different locales isn't a trivial process, I would recommend a ICU C# wrapper instead. If you know before hand which locale/language will be used, then I guess regex should be sufficient most of the times.
